package cn.search.pojo;
// Generated 2018-10-10 0:36:32 by Hibernate Tools 4.3.1.Final

/**
 * Urlinfo generated by hbm2java
 */
public class Urlinfo implements java.io.Serializable {

	private Integer uid;
	private Urlsortinfo urlsortinfo;
	private String urlName;
	private String urlWeblink;

	public Urlinfo() {
	}

	public Urlinfo(String urlName, String urlWeblink) {
		this.urlName = urlName;
		this.urlWeblink = urlWeblink;
	}

	public Urlinfo(Urlsortinfo urlsortinfo, String urlName, String urlWeblink) {
		this.urlsortinfo = urlsortinfo;
		this.urlName = urlName;
		this.urlWeblink = urlWeblink;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Urlsortinfo getUrlsortinfo() {
		return this.urlsortinfo;
	}

	public void setUrlsortinfo(Urlsortinfo urlsortinfo) {
		this.urlsortinfo = urlsortinfo;
	}

	public String getUrlName() {
		return this.urlName;
	}

	public void setUrlName(String urlName) {
		this.urlName = urlName;
	}

	public String getUrlWeblink() {
		return this.urlWeblink;
	}

	public void setUrlWeblink(String urlWeblink) {
		this.urlWeblink = urlWeblink;
	}

	@Override
	public String toString() {
		return "Urlinfo [uid=" + uid + ", urlsortinfo="  + ", urlName=" + urlName + ", urlWeblink="
				+ urlWeblink + "]";
	}
	
	

	

}
