package cn.search.pojo;
// Generated 2018-10-10 0:36:32 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Urlsortinfo generated by hbm2java
 */
public class Urlsortinfo implements java.io.Serializable {

	private Integer urlsortId;
	private String urlsortName;
	private Set urlinfos = new HashSet(0);

	public Urlsortinfo() {
	}

	public Urlsortinfo(String urlsortName) {
		this.urlsortName = urlsortName;
	}

	public Urlsortinfo(String urlsortName, Set urlinfos) {
		this.urlsortName = urlsortName;
		this.urlinfos = urlinfos;
	}

	public Integer getUrlsortId() {
		return this.urlsortId;
	}

	public void setUrlsortId(Integer urlsortId) {
		this.urlsortId = urlsortId;
	}

	public String getUrlsortName() {
		return this.urlsortName;
	}

	public void setUrlsortName(String urlsortName) {
		this.urlsortName = urlsortName;
	}

	public Set getUrlinfos() {
		return this.urlinfos;
	}

	public void setUrlinfos(Set urlinfos) {
		this.urlinfos = urlinfos;
	}

	@Override
	public String toString() {
		return "Urlsortinfo [urlsortId=" + urlsortId + ", urlsortName=" + urlsortName + ", urlinfos=" + urlinfos + "]";
	}

}
