package cn.search.pojo;
// Generated 2018-10-10 0:36:32 by Hibernate Tools 4.3.1.Final

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userAccount;
	private String userPwd;

	public Userinfo() {
	}

	public Userinfo(String userName, String userAccount, String userPwd) {
		this.userName = userName;
		this.userAccount = userAccount;
		this.userPwd = userPwd;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@Override
	public String toString() {
		return "Userinfo [userId=" + userId + ", userName=" + userName + ", userAccount=" + userAccount + ", userPwd="
				+ userPwd + "]";
	}
	

}
